name: "Build and push container image"

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup tags to be used for docker images
      - name: Compute labels and tags
        uses: docker/metadata-action@v4
        id: docker_meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/clingo-performance-study

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "linux/amd64,linux/arm64"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Deploy
        uses: docker/build-push-action@v2
        with:
          context: ./container
          push: ${{ github.event_name == 'push' }}
          platforms: "linux/amd64,linux/arm64"
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          # See: https://github.com/moby/buildkit#github-actions-cache-experimental
          cache-from: |
            type=gha
          cache-to: |
            type=gha,mode=max
